version: "3.9"

services:
  db:
    image: "postgres"
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"
  server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    tty: true
    working_dir: /usr/src/app
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb?schema=public"